# Set the version of docker compose to use
version: '3'

# The containers that compose the project
services:
  database:
    image: 'postgres:latest'
    restart: always
    container_name: api-db-tests
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests